### ISSUE TITLE
Create Enemy Base Blueprint

### ISSUE THREAD

**Issue by ApoorvaAditya** [Milosz11/FinalProject#1]
- [x] Health variable
- [x] IsInvincible variable
- [x] Damageable interface

**Comment by ApoorvaAditya** [comment]
- [ ] Health variable
- [ ] OnTakeDamage event
- [ ] DealDamage event

**Comment by Milosz11** [comment]
I think static mesh will have to be customized in the child classes, same thing with movement, as different enemies will have different behaviors.

**Comment by ApoorvaAditya** [comment]
Yeah you're right. I'll remove that from the list of tasks.
